spring.application.name=olympo-academy
#this allows us to use .html 
spring.mustache.suffix=.html
#it shows detailed information about web requests in the logs
logging.level.org.springframework.web=DEBUG 
#connect to our mysql database 
spring.datasource.url=jdbc:mysql://localhost:3306/olympo_academy_db
spring.datasource.username=root
spring.datasource.password=petanqueros123
spring.jpa.hibernate.ddl-auto=update
#server.port = 8443